services:
  - type: web
    name: calorie-tracker-api
    env: python
    buildCommand: |
      pip install -r requirements.txt
      curl -L "https://drive.google.com/uc?export=download&id=1FCv3UeEIfw4Qs_A9U74YjbT85XeNrUyr" -o model_trained_101class.keras
    startCommand: uvicorn app:app --host=0.0.0.0 --port=10000
    autoDeploy: true
    envVars:
      - key: MODEL_PATH
        value: model_trained_101class.keras
    plan: starter
    region: oregon
